#!/bin/sh

source /etc/manjaro/functions

MISOVAR="$(kernel_cmdline misovar lang:en_US,keymap:en_US,timezone:Canada/Pacific)"
LOCALE="$(echo "$MISOVAR" | cut -d, -f1 | cut -d: -f2)"
KEYMAP="$(echo "$MISOVAR" | cut -d, -f2 | cut -d: -f2)"
TIMEZONE="$(echo "$MISOVAR" | cut -d, -f3 | cut -d: -f2)"
VIDEO="$(echo "$MISOVAR" | cut -d, -f4 | cut -d: -f2)"
COMPOSITE="$(echo "$MISOVAR" | cut -d, -f5 | cut -d: -f2)"
CONSOLEFONT="$(kernel_cmdline vconsole.font)"
CONSOLEMAP="$(kernel_cmdline vconsole.font.map)"
USENONFREE="$(kernel_cmdline nonfree no)"
PACMAN_LNG="pacman --config /opt/manjaro/pacman-lng.conf --noconfirm --noprogressbar"
arch=$(uname -m)
_kernver=$(uname -r)
EXTRAMODULES=extramodules-${_kernver%.*}-MANJARO

## Systemd should do it
# scan_swap
swapdev="$(fdisk -l 2>/dev/null | grep swap | cut -d' ' -f1)"
if [ -e "${swapdev}" ]; then
	swapon ${swapdev}
	echo "${swapdev} swap swap defaults 0 0 #configured by manjaroiso" >>/etc/fstab
fi

# edit /etc/locale.conf & /etc/environment
echo "LANG=${LOCALE}.UTF-8" > /etc/locale.conf
echo "LC_COLLATE=C" >> /etc/locale.conf
echo "LANG=${LOCALE}.UTF-8" >> /etc/environment

# prepare_locale_gen
for i in $(grep "^LANG" /etc/locale.conf | sed -e 's/.*=//g' -e's/\..*//g'); do
	sed -i -e "s/^#$i/$i/g" /etc/locale.gen
done
if [ "$LOCALE" != "en_US.UTF-8" ]; then
        sed -i -e "s/^#en_US/en_US/g" /etc/locale.gen
fi
/usr/sbin/locale-gen > /dev/null

# set_timezone
ln -sf "/usr/share/zoneinfo/${TIMEZONE}" /etc/localtime  

# configure alsa
set_alsa

# save settings
alsactl -f /etc/asound.state store &>/dev/null

# enable default mirror
cp -f /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
sed -i -e 's~^.*mirrors.mycraft.eu.*~Server = http://mirrors.mycraft.eu/manjaro/$repo/$arch~' /etc/pacman.d/mirrorlist

# update_pacman_databases
pacman -Syy &> /dev/null

# hwdetect_graphics

# TODO: fix in mhwd
mkdir -p /var/lib/mhwd/local/{pci,usb}

if [ -e "/opt/manjaro/pacman-gfx.conf" ] ; then
   if  [ "${USENONFREE}" == "yes" ] || [ "${USENONFREE}" == "true" ]; then
   	if  [ "${VIDEO}" == "vesa" ]; then
		/usr/bin/mhwd --install pci video-vesa --pmconfig "/opt/manjaro/pacman-gfx.conf"
	else
		/usr/bin/mhwd --auto pci nonfree 0300 --pmconfig "/opt/manjaro/pacman-gfx.conf"
	fi
   else
   	if  [ "${VIDEO}" == "vesa" ]; then
		/usr/bin/mhwd --install pci video-vesa --pmconfig "/opt/manjaro/pacman-gfx.conf"
	else
		/usr/bin/mhwd --auto pci free 0300 --pmconfig "/opt/manjaro/pacman-gfx.conf"
	fi
   fi
fi	

# do_makeuser
addgroups="video,audio,power,disk,storage,optical,network,lp,scanner"
useradd -m -p "" -g users -G $addgroups manjaro
sed -i "s#manjaro.*#manjaro:\$1\$uYIrxnwJ\$a5wTa84YxxYmD.sKX/Lll1:14942:0:99999:7:::#" /etc/shadow

# do_configsforroot
cp -a /etc/skel/. /root/

# do_setuplightdm
if [ -e "/usr/sbin/lightdm" ] ; then
   mkdir -p /run/lightdm > /dev/null
   getent group lightdm > /dev/null 2>&1 || groupadd -g 620 lightdm
   getent passwd lightdm > /dev/null 2>&1 || useradd -c 'LightDM Display Manager' -u 620 -g lightdm -d /var/run/lightdm -s /sbin/nologin lightdm
   passwd -l lightdm > /dev/null
   chown -R lightdm:lightdm /var/run/lightdm > /dev/null
   #sed -i -e 's/^.*user-session=.*/user-session=xfce/' /etc/lightdm/lightdm.conf
   sed -i -e 's/^.*autologin-user=.*/autologin-user=manjaro/' /etc/lightdm/lightdm.conf
   sed -i -e 's/^.*autologin-user-timeout=.*/autologin-user-timeout=0/' /etc/lightdm/lightdm.conf
   sed -i -e 's/^.*pam-service=.*/pam-service=lightdm-autologin/' /etc/lightdm/lightdm.conf
   chmod +r /etc/lightdm/lightdm.conf
   # livecd fix
   echo "d /run/lightdm 0770 lightdm lightdm -" > /usr/lib/tmpfiles.d/lightdm.conf
fi

# do_setupkdm
if [ -e "/usr/share/config/kdm/kdmrc" ] ; then
   getent group kdm >/dev/null 2>&1 || groupadd -g 135 kdm &>/dev/null
   getent passwd kdm >/dev/null 2>&1 || useradd -u 135 -g kdm -d /var/lib/kdm -s /bin/false -r -M kdm &>/dev/null
   chown -R 135:135 var/lib/kdm &>/dev/null
   xdg-icon-resource forceupdate --theme hicolor &> /dev/null
   update-desktop-database -q
   sed -i -e 's/^.*AutoLoginUser=.*/AutoLoginUser=manjaro/' /usr/share/config/kdm/kdmrc
   sed -i -e 's/^.*AutoLoginPass=.*/AutoLoginPass=manjaro/' /usr/share/config/kdm/kdmrc
fi

# do_setupgdm
if [ -e "/usr/sbin/gdm" ] ; then
  getent group gdm >/dev/null 2>&1 || groupadd -g 120 gdm
  getent passwd gdm > /dev/null 2>&1 || usr/sbin/useradd -c 'Gnome Display Manager' -u 120 -g gdm -d /var/lib/gdm -s /sbin/nologin gdm
  passwd -l gdm > /dev/null
  chown -R gdm:gdm /var/lib/gdm &> /dev/null
fi

# do_setuplxdm
if [ -e "/usr/sbin/lxdm" ] ; then
   if [ -z "`getent group "lxdm" 2> /dev/null`" ]; then
        groupadd --system lxdm > /dev/null
   fi
   sed -i -e 's/^.*autologin=.*/autologin=manjaro/' /etc/lxdm/lxdm.conf
   if [ -e "/bootmnt/manjaro/${arch}/xfce-image.sqfs" ] ; then
      sed -i -e 's|^.*session=.*|session=/usr/bin/startxfce4|' /etc/lxdm/lxdm.conf
   fi
   chgrp -R lxdm /var/lib/lxdm > /dev/null
   chgrp lxdm /etc/lxdm/lxdm.conf > /dev/null
   chmod +r /etc/lxdm/lxdm.conf > /dev/null
fi

# do_fix_perms
chown root:root /etc/sudoers
chmod 440 /etc/sudoers

# fix_gnome_apps
glib-compile-schemas /usr/share/glib-2.0/schemas
gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
dconf update
if [ -e "/usr/bin/gnome-keyring-daemon" ] ; then
   setcap cap_ipc_lock=ep /usr/bin/gnome-keyring-daemon &> /dev/null
fi

# fix_ping_installation
setcap cap_net_raw=ep /usr/bin/ping &> /dev/null
setcap cap_net_raw=ep /usr/bin/ping6 &> /dev/null

# do_lang_settings
# setup locales
_do_locales

# installing localization packages
if [ -e "/bootmnt/manjaro/${arch}/lng-image.sqfs" ] ; then
   _configure_translation_pkgs
   if [ ! -e "/bootmnt/manjaro/${arch}/kde-image.sqfs" ] ; then
      PACMAN_LNG_INST_KDE=""
   fi
   ${PACMAN_LNG} -Sy ${PACMAN_LNG_INST} ${PACMAN_LNG_INST_KDE} &> /dev/null
fi

# add BROWSER var
echo "BROWSER=/usr/bin/xdg-open" >> /etc/environment

# load keys
loadkeys $(cat /etc/vconsole.conf | grep "KEYMAP=" | cut -d= -f2)

# depmod extramodules
depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)

# check if we are running inside a virtual machine and unistall kalu
DESTDIR="/"
if [ -e "/usr/bin/kalu" ] ; then
   _rm_kalu
fi
