#!/bin/sh

# kernel_cmdline <param> <default>
# Looks for a parameter on the kernel's boot-time command line.
#
# returns: 0 if param was found. Also prints its value if it was a K=V param.
#          1 if it was not. Also prints value passed as <default>
#
kernel_cmdline ()
{
    for param in $(/bin/cat /proc/cmdline); do
        case "${param}" in
            $1=*) echo "${param##*=}"; return 0 ;;
            $1) return 0 ;;
            *) continue ;;
        esac
    done
    [ -n "${2}" ] && echo "${2}"
    return 1
}

MISOVAR="$(kernel_cmdline misovar lang:en_US,keymap:en_US,timezone:Canada/Pacific)"
LOCALE="$(echo "$MISOVAR" | cut -d, -f1 | cut -d: -f2)"
KEYMAP="$(echo "$MISOVAR" | cut -d, -f2 | cut -d: -f2)"
TIMEZONE="$(echo "$MISOVAR" | cut -d, -f3 | cut -d: -f2)"
VIDEO="$(echo "$MISOVAR" | cut -d, -f4 | cut -d: -f2)"
COMPOSITE="$(echo "$MISOVAR" | cut -d, -f5 | cut -d: -f2)"
CONSOLEFONT="$(kernel_cmdline vconsole.font)"
CONSOLEMAP="$(kernel_cmdline vconsole.font.map)"
USENONFREE="$(kernel_cmdline nonfree no)"

## Systemd should do it
#scan_swap
swapdev="$(fdisk -l 2>/dev/null | grep swap | cut -d' ' -f1)"
if [ -e "${swapdev}" ]; then
	swapon ${swapdev}
	echo "${swapdev} swap swap defaults 0 0 #configured by manjaroiso" >>/etc/fstab
fi

#edit /etc/locale.conf & /etc/environment
echo "LANG=${LOCALE}.UTF-8" > /etc/locale.conf
echo "LC_COLLATE=C" >> /etc/locale.conf
echo "LANG=${LOCALE}.UTF-8" >> /etc/environment

#prepare_locale_gen
for i in $(grep "^LANG" /etc/locale.conf | sed -e 's/.*=//g' -e's/\..*//g'); do
	sed -i -e "s/^#$i/$i/g" /etc/locale.gen
done
if [ "$LOCALE" != "en_US.UTF-8" ]; then
        sed -i -e "s/^#en_US/en_US/g" /etc/locale.gen
fi
/usr/sbin/locale-gen > /dev/null

#set_timezone
ln -sf "/usr/share/zoneinfo/${TIMEZONE}" /etc/localtime  

#set_alsa
	# amixer binary
	local alsa_amixer="/usr/bin/amixer"

	# enable all known (tm) outputs
	$alsa_amixer -c 0 sset "Master" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "Front" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "Side" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "Surround" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "Center" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "LFE" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "Headphone" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "Speaker" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "PCM" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "Line" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "External" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "FM" 50% unmute &> /dev/null
	$alsa_amixer -c 0 sset "Master Mono" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "Master Digital" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "Analog Mix" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "Aux" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "Aux2" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "PCM Center" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "PCM Front" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "PCM LFE" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "PCM Side" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "PCM Surround" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "Playback" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "PCM,1" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "DAC" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "DAC,0" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "DAC,0" -12dB &> /dev/null
	$alsa_amixer -c 0 sset "DAC,1" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "DAC,1" -12dB &> /dev/null
	$alsa_amixer -c 0 sset "Synth" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "CD" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "Wave" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "Music" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "AC97" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "Analog Front" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "VIA DXS,0" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "VIA DXS,1" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "VIA DXS,2" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "VIA DXS,3" 70% unmute &> /dev/null

	# set input levels
	$alsa_amixer -c 0 sset "Mic" 70% mute &>/dev/null
	$alsa_amixer -c 0 sset "IEC958" 70% mute &>/dev/null

	# special stuff
	$alsa_amixer -c 0 sset "Master Playback Switch" on &>/dev/null
	$alsa_amixer -c 0 sset "Master Surround" on &>/dev/null
	$alsa_amixer -c 0 sset "SB Live Analog/Digital Output Jack" off &>/dev/null
	$alsa_amixer -c 0 sset "Audigy Analog/Digital Output Jack" off &>/dev/null

	# save settings
	alsactl -f /etc/asound.state store &>/dev/null

# enable default mirror
cp -f /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
sed -i -e 's~^.*repo.manjaro.org.uk.*~Server = http://repo.manjaro.org.uk/$repo/$arch~' /etc/pacman.d/mirrorlist

#update_pacman_databases
pacman -Syy &> /dev/null

#hwdetect_graphics

# TODO: fix in mhwd
mkdir -p /var/lib/mhwd/local/{pci,usb}

if [ -e "/opt/manjaro/pacman-gfx.conf" ] ; then
   if  [ "${USENONFREE}" == "yes" ] || [ "${USENONFREE}" == "true" ]; then
   	if  [ "${VIDEO}" == "vesa" ]; then
		/usr/bin/mhwd --install pci video-vesa --pmconfig "/opt/manjaro/pacman-gfx.conf"
	else
		/usr/bin/mhwd --auto pci nonfree 0300 --pmconfig "/opt/manjaro/pacman-gfx.conf"
	fi
   else
   	if  [ "${VIDEO}" == "vesa" ]; then
		/usr/bin/mhwd --install pci video-vesa --pmconfig "/opt/manjaro/pacman-gfx.conf"
	else
		/usr/bin/mhwd --auto pci free 0300 --pmconfig "/opt/manjaro/pacman-gfx.conf"
	fi
   fi
fi	

#do_makeuser
addgroups="video,audio,power,disk,storage,optical,network,lp,scanner"
useradd -m -p "" -g users -G $addgroups manjaro
sed -i "s#manjaro.*#manjaro:\$1\$uYIrxnwJ\$a5wTa84YxxYmD.sKX/Lll1:14942:0:99999:7:::#" /etc/shadow

#do_configsforroot
cp -fR /etc/skel/.* /root/
cp -fR /etc/skel/* /root/

#do_setuplightdm
if [ -e "/usr/sbin/lightdm" ] ; then
   mkdir -p /run/lightdm > /dev/null
   chown -R lightdm:lightdm /run/lightdm > /dev/null
   #sed -i -e 's/^.*user-session=.*/user-session=xfce/' /etc/lightdm/lightdm.conf
   sed -i -e 's/^.*autologin-user=.*/autologin-user=manjaro/' /etc/lightdm/lightdm.conf
   sed -i -e 's/^.*autologin-user-timeout=.*/autologin-user-timeout=0/' /etc/lightdm/lightdm.conf
   sed -i -e 's/^.*pam-service=.*/pam-service=lightdm-autologin/' /etc/lightdm/lightdm.conf
   chmod +r /etc/lightdm/lightdm.conf
fi

#do_setupkdm
if [ -e "/usr/share/config/kdm/kdmrc" ] ; then
   sed -i -e 's/^.*AutoLoginUser=.*/AutoLoginUser=manjaro/' /usr/share/config/kdm/kdmrc
   sed -i -e 's/^.*AutoLoginPass=.*/AutoLoginPass=manjaro/' /usr/share/config/kdm/kdmrc
fi

#do_setupgdm
if [ -e "/usr/sbin/gdm" ] ; then
  chown -R gdm:gdm /var/lib/gdm &> /dev/null
fi

#do_setuplxdm
if [ -e "/usr/sbin/lxdm" ] ; then
   sed -i -e 's/^.*autologin=.*/autologin=manjaro/' /etc/lxdm/lxdm.conf
   chown root:lxdm /etc/lxdm/lxdm.conf > /dev/null
   chown -R root:lxdm /var/lib/lxdm > /dev/null
   chmod +r /etc/lxdm/lxdm.conf
fi

#do_fix_perms
chown root:root /etc/sudoers
chmod 440 /etc/sudoers

#fix_gnome_apps
glib-compile-schemas usr/share/glib-2.0/schemas
if [ -e "/usr/bin/gnome-keyring-daemon" ] ; then
   setcap cap_ipc_lock=ep /usr/bin/gnome-keyring-daemon &> /dev/null
fi

#do_lang_settings
 	# Determind which language we are using
	if [ "$(echo "${KEYMAP}" | grep "en_US")" != "" ]; then
		# Setup system for the American language
		
		# Set American Xorg keyboard layout
		sed -i 's#Ident	elifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "us"#'       /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=us/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "en_GB")" != "" ]; then
		# Setup system for the British language
		
		# Set British Xorg keyboard layout
		sed -i 's#Ident	elifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "gb"#'       /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=uk/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "be_BY")" != "" ]; then
		# Setup system for the Belarusian language
		
		# Set Belarusian Xorg keyboard layout
		sed -i 's#Identifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "be"#' /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=be/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "pt_BR")" != "" ]; then
		# Setup system for the Brazilian language
		
		# Set Brazilian Xorg keyboard layout
		sed -i 's#Ident	elifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "pt"#'       /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=pt/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "bg_BG")" != "" ]; then
		# Setup system for the Bulgarian language
		
		# Set Bulgarian Xorg keyboard layout
		sed -i 's#Ident	elifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "bg"#'       /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=bg/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "da_DK")" != "" ]; then
		# Setup system for the Danish language
		
		# Set Danish Xorg keyboard layout
		sed -i 's#Ident	elifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "dk"#'       /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=dk/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "fr_BE")" != "" ]; then
		# Setup system for the Belgian language
		
		# Set Belgian Xorg keyboard layout
		sed -i 's#Ident	elifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "be-latin1"#'       /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=be-latin1/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "fr_FR")" != "" ]; then
		# Setup system for the French language
		
		# Set French Xorg keyboard layout
		sed -i 's#Identifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "fr"#'       /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=fr/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "fr_CA")" != "" ]; then
		# Setup system for the French Canada language
		
		# Set French Canada Xorg keyboard layout
		sed -i 's#Identifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "cf"#'       /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=cf/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "de_DE")" != "" ]; then
		# Setup system for the German language
		
		# Set German Xorg keyboard layout
		sed -i 's#Identifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "de"\n        Option "XkbVariant" "nodeadkeys"#' /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=de/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "is_IS")" != "" ]; then
		# Setup system for the Icelandic language
		
		# Set Icelandic Xorg keyboard layout
		sed -i 's#Ident	elifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "is"#'       /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=is/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "it_IT")" != "" ]; then
		# Setup system for the Italian language
		
		# Set Italian Xorg keyboard layout
		sed -i 's#Ident	elifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "it"#'       /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=it/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "nn_NO")" != "" ]; then
		# Setup system for the Nynorsk language
		
		# Set Nynorsk Xorg keyboard layout
		sed -i 's#Ident	elifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "no"#'       /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=no-latin1/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "pl_PL")" != "" ]; then
		# Setup system for the Polish language
		
		# Set Polish Xorg keyboard layout
		sed -i 's#Ident	elifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "pl"#'       /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=pl/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "pt_PT")" != "" ]; then
		# Setup system for the Portuguese language
		
		# Set Portuguese Xorg keyboard layout
		sed -i 's#Ident	elifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "pt"#'       /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=pt/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "ro_RO")" != "" ]; then
		# Setup system for the Romanian language
		
		# Set Romanian Xorg keyboard layout
		sed -i 's#Ident	elifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "ro"#'       /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=ro/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "ru_RU")" != "" ]; then
		# Setup system for the Russian language
		
		# Set Russian Xorg keyboard layout
		sed -i 's#Identifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "ru"#'       /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=ru/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "es_AR")" != "" ]; then
		# Setup system for the Argentinian language
		
		# Set Argentinian Xorg keyboard layout
		sed -i 's#Identifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "la-latin1"#'       /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=la-latin1/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "es_ES")" != "" ]; then
		# Setup system for the Spanish language
		
		# Set Spanish Xorg keyboard layout
		sed -i 's#Identifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "es"#'       /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=es/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "sv_SE")" != "" ]; then
		# Setup system for the Swedish language
		
		# Set Swedish Xorg keyboard layout
		sed -i 's#Ident	elifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "sv-latin1"#'       /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=sv-latin1/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "tr_TR")" != "" ]; then
		# Setup system for the Turkish language
		
		# Set Turkish Xorg keyboard layout
		sed -i 's#Identifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "tr"#'       /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=trq/' /etc/vconsole.conf

	elif [ "$(echo "${KEYMAP}" | grep "uk_UA")" != "" ]; then
		# Setup system for the Ukrainian language
		
		# Set Ukrainian Xorg keyboard layout
		sed -i 's#Ident	elifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "ua"#'       /etc/X11/xorg.conf.d/10-evdev.conf
                sed -i -e 's/^.*KEYMAP=.*/KEYMAP=ua/' /etc/vconsole.conf
	fi

#load keys
loadkeys $(cat /etc/vconsole.conf | grep "KEYMAP=" | cut -d= -f2)
