#!/bin/sh

# check if we have a internet connection
ping_check=$(LC_ALL=C ping -c 1 www.manjaro.org | grep "1 received")

if [ "${ping_check}" != "" ] ; then
    wget -O /etc/pacman.d/mirrorlist http://git.manjaro.org/packages-sources/basis/blobs/raw/master/pacman-mirrorlist/mirrorlist &>/dev/null
    sed -i 's/# Server/Server/g' -i /etc/pacman.d/mirrorlist
    # rankmirrors
    cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
    rankmirrors -v -n 4 /etc/pacman.d/mirrorlist.backup > /etc/pacman.d/mirrorlist
else
    # enable default mirror
    sed -i -e 's~^.*repo.manjaro.org.uk.*~Server = http://repo.manjaro.org.uk/$repo/$arch~' /etc/pacman.d/mirrorlist
fi
