#!/bin/sh

if [[ ! -e /tmp/mirrorcheck.running ]]; then

	echo "running" > /tmp/mirrorcheck.running

	# update mirrorlist
	cp -f /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
	wget -O /etc/pacman.d/mirrorlist.new http://git.manjaro.org/packages-sources/basis/blobs/raw/master/pacman-mirrorlist/mirrorlist &>/dev/null

	# rankmirrors
	sed -i 's/# Server/Server/g' -i /etc/pacman.d/mirrorlist.new
	rankmirrors -v -n 4 /etc/pacman.d/mirrorlist.new > /etc/pacman.d/mirrorlist

	# check mirrorlist
	if [ $(cat /etc/pacman.d/mirrorlist | grep "Server =" -c1) == "" ] ; 
	then 
	    echo "Error: invalid mirrorlist! Enable default server"
	    # enable default mirror
	    cp -f /etc/pacman.d/mirrorlist.backup /etc/pacman.d/mirrorlist
 	   sed -i -e 's~^.*repo.manjaro.org.uk.*~Server = http://repo.manjaro.org.uk/$repo/$arch~' /etc/pacman.d/mirrorlist
	fi

	# update databases
	pacman -Syy

	rm /tmp/mirrorcheck.running
fi


