#!/bin/bash
# installer wrapper

TITLE="Manjaro Linux Installation Framework (v0.8.2)"
_mainmenuhelp="Use ↓ and ↑ to choose an entry, enter to launch it." 
_mainmenulabel="Wrapper menu"
_stableinstaller="Use stable installer"
_testinginstaller="Use testing installer (EFI support)"
_quittext="Quit"
_exitwrapper="Quit Installer Wrapper?"
_cancelwrapper="Cancel installation?"
_wrapperwelcomemessage="Welcome to the Manjaro Linux Installation Framework. \nWe offer two versions of our CLI installer. \nOur 'stable installer' is known to work but don't get new features added. \nWith our 'testing installer' you have new features like EFI, btrfs and software raid support. \n\nChoose the installer which fit's best for you."

_yes="Yes"
_no="No"
_cancel="Cancel"

ANSWER="/tmp/.setup"

# main menu selection tracker
CURRENT_SELECTION=""

DIALOG() {
   # parameters: see dialog(1)
   # returns: whatever dialog did
   dialog --backtitle "$TITLE" --aspect 15 --yes-label "$_yes" --no-label "$_no" --cancel-label "$_cancel" "$@"
   return $?
}

mainmenu()
{
    if [ -n "$CURRENT_SELECTION" ]; then
        DEFAULT="--default-item $CURRENT_SELECTION"
    else
        DEFAULT=""
    fi
    DIALOG $DEFAULT --title " ${_mainmenulabel} " \
        --menu "${_mainmenuhelp}" 16 55 8 \
        "1" "${_stableinstaller}" \
        "2" "${_testinginstaller}" \
        "3" "${_quittext}" 2>$ANSWER
    CURRENT_SELECTION="$(cat $ANSWER)"
    case $(cat $ANSWER) in
        "1")
            ./setup-0.8
            exit 0
        ;;
        "2")
            ./setup-0.9
            exit 0
        ;;
        "3")
            if DIALOG --yesno "${_exitwrapper}" 6 40;then
             exit 0
            fi
        ;;
        *)
            if DIALOG --yesno "${_cancelwrapper}" 6 40;then
             exit 0
            fi
        ;;
    esac
}

#####################
## begin execution ##

# do UID checking here so someone can at least get usage instructions
if [ "$EUID" != "0" ]; then
    echo "error: This script must be run as root."
    exit 1
fi

# force to use english
export LANG=en_US.UTF-8
export LC_MESSAGES=en_US.UTF-8

DIALOG --msgbox "${_wrapperwelcomemessage}" 12 65

while true; do
    mainmenu
done

exit 0
