#!/bin/bash
# installer wrapper

TITLE="Manjaro Linux Installation Framework (v0.8.2)"

_yes="Yes"
_no="No"
_cancel="Cancel"

ANSWER="/tmp/.setup"

# main menu selection tracker
CURRENT_SELECTION=""

DIALOG() {
   # parameters: see dialog(1)
   # returns: whatever dialog did
   dialog --backtitle "$TITLE" --aspect 15 --yes-label "$_yes" --no-label "$_no" --cancel-label "$_cancel" "$@"
   return $?
}

kernel_cmdline ()
{
    for param in $(/bin/cat /proc/cmdline); do
        case "${param}" in
            $1=*) echo "${param##*=}"; return 0 ;;
            $1) return 0 ;;
            *) continue ;;
        esac
    done
    [ -n "${2}" ] && echo "${2}"
    return 1
}

mainmenu()
{
    if [ -n "$CURRENT_SELECTION" ]; then
        DEFAULT="--default-item $CURRENT_SELECTION"
    else
        DEFAULT=""
    fi
    DIALOG $DEFAULT --title " ${_mainmenulabel} " \
        --menu "${_mainmenuhelp}" 16 55 8 \
        "1" "${_stableinstaller}" \
        "2" "${_testinginstaller}" \
        "3" "${_quittext}" 2>$ANSWER
    CURRENT_SELECTION="$(cat $ANSWER)"
    case $(cat $ANSWER) in
        "1")
            DIALOG --infobox "${_loadinginstaller}" 6 40
            cd /etc/manjaro
            ./setup-0.8
            exit 0
        ;;
        "2")
            DIALOG --infobox "${_loadinginstaller}" 6 40
            cd /etc/manjaro
            ./setup-0.9
            exit 0
        ;;
        "3")
            if DIALOG --yesno "${_exitwrapper}" 6 40;then
             exit 0
            fi
        ;;
        *)
            if DIALOG --yesno "${_cancelwrapper}" 6 40;then
             exit 0
            fi
        ;;
    esac
}

#####################
## begin execution ##

# do UID checking here so someone can at least get usage instructions
if [ "$EUID" != "0" ]; then
    echo "error: This script must be run as root."
    exit 1
fi

# force to use english
export LANG=en_US.UTF-8
export LC_MESSAGES=en_US.UTF-8

MISOVAR="$(kernel_cmdline misovar lang:en_US,keymap:en_US,timezone:Canada/Pacific)"
LOCALE="$(echo "$MISOVAR" | cut -d, -f1 | cut -d: -f2)"

# Translation
# English
. setup-en.lng
# Turkish
if [ "${LOCALE}" = "tr_TR" ]; then
   . setup-tr.lng
fi

DIALOG --msgbox "${_wrapperwelcomemessage}" 12 65

while true; do
    mainmenu
done

exit 0
