#!/bin/sh

# kernel_cmdline <param> <default>
# Looks for a parameter on the kernel's boot-time command line.
#
# returns: 0 if param was found. Also prints its value if it was a K=V param.
#          1 if it was not. Also prints value passed as <default>
#
kernel_cmdline ()
{
    for param in $(/bin/cat /proc/cmdline); do
        case "${param}" in
            $1=*) echo "${param##*=}"; return 0 ;;
            $1) return 0 ;;
            *) continue ;;
        esac
    done
    [ -n "${2}" ] && echo "${2}"
    return 1
}

LOCALE="$(kernel_cmdline locale.LANG en_US.utf8)"
TIMEZONE="$(kernel_cmdline timezone UTC)"
KEYMAP="$(kernel_cmdline vconsole.keymap us)"
CONSOLEFONT="$(kernel_cmdline vconsole.font)"
CONSOLEMAP="$(kernel_cmdline vconsole.font.map)"

## Systemd should do it
#scan_swap
swapdev="$(fdisk -l 2>/dev/null | grep swap | cut -d' ' -f1)"
if [ -e "${swapdev}" ]; then
	swapon ${swapdev}
	echo "${swapdev} swap swap defaults 0 0 #configured by manjaroiso" >>/etc/fstab
fi

#edit /etc/locale.conf & /etc/environment
echo "LANG=${LOCALE}" > /etc/locale.conf
echo "LC_COLLATE=C" >> /etc/locale.conf
echo "LANG=${LOCALE}" >> /etc/environment

#prepare_locale_gen
for i in $(grep "^LANG" /etc/locale.conf | sed -e 's/.*=//g' -e's/\..*//g'); do
	sed -i -e "s/^#$i/$i/g" /etc/locale.gen
done
if [ "$LOCALE" != "en_US.utf8" ]; then
        sed -i -e "s/^#en_US/en_US/g" /etc/locale.gen
fi
/usr/sbin/locale-gen > /dev/null

#set_timezone
ln -sf "/usr/share/zoneinfo/${TIMEZONE}" /etc/localtime  

#set_alsa
	# amixer binary
	local alsa_amixer="/usr/bin/amixer"

	# enable all known (tm) outputs
	$alsa_amixer -c 0 sset "Master" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "Front" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "Side" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "Surround" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "Center" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "LFE" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "Headphone" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "Speaker" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "PCM" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "Line" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "External" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "FM" 50% unmute &> /dev/null
	$alsa_amixer -c 0 sset "Master Mono" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "Master Digital" 70% unmute &>/dev/null
	$alsa_amixer -c 0 sset "Analog Mix" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "Aux" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "Aux2" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "PCM Center" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "PCM Front" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "PCM LFE" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "PCM Side" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "PCM Surround" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "Playback" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "PCM,1" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "DAC" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "DAC,0" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "DAC,0" -12dB &> /dev/null
	$alsa_amixer -c 0 sset "DAC,1" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "DAC,1" -12dB &> /dev/null
	$alsa_amixer -c 0 sset "Synth" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "CD" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "Wave" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "Music" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "AC97" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "Analog Front" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "VIA DXS,0" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "VIA DXS,1" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "VIA DXS,2" 70% unmute &> /dev/null
	$alsa_amixer -c 0 sset "VIA DXS,3" 70% unmute &> /dev/null

	# set input levels
	$alsa_amixer -c 0 sset "Mic" 70% mute &>/dev/null
	$alsa_amixer -c 0 sset "IEC958" 70% mute &>/dev/null

	# special stuff
	$alsa_amixer -c 0 sset "Master Playback Switch" on &>/dev/null
	$alsa_amixer -c 0 sset "Master Surround" on &>/dev/null
	$alsa_amixer -c 0 sset "SB Live Analog/Digital Output Jack" off &>/dev/null
	$alsa_amixer -c 0 sset "Audigy Analog/Digital Output Jack" off &>/dev/null

	# save settings
	alsactl -f /etc/asound.state store &>/dev/null

## Wait for the last mhwd binary
#hwdetect_graphics
#local USENONFREE="$(kernel_cmdline nonfree no)"
#
#if  [ "${USENONFREE}" == "yes" ] || [ "${USENONFREE}" == "true" ]; then
#	/usr/bin/mhwd -c 0300 -nf
#else
#	/usr/bin/mhwd -c 0300
#fi	

## Install xf86-video driver

if [ -e "/opt/manjaro/pacman-gfx.conf" ] ; then
   driver=`hwinfo --gfxcard | grep -m1 'Module:' | cut -d: -f2 | sed s'/ //'g`

   # replace nv with nouveau
   if [ "$driver" == "nv" ] ; then
      driver="nouveau"
   fi

   # replace radeon with ati
   if [ "$driver" == "radeon" ] ; then
      driver="ati"
   fi

   # replace i915 with intel
   if [ "$driver" == "i915" ] ; then
      driver="intel"
   fi

   # check if some driver was found
   if [ "x$driver" != "x" ] ; then
      dri="$driver-dri"
      if [ "`uname -m`" == "x86_64" ] ; then
         dri64="lib32-$driver-dri"
      else
         dri64=""
      fi
      driver="xf86-video-$driver"
   fi

   # check if driver exists
   if [ "`ls /opt/manjaro/pkgs/$driver* | grep "ls:"`" != "" ] ; then
      driver=""
   fi

   # check if dri exists
   if [ "`ls /opt/manjaro/pkgs/$dri* | grep "ls:"`" != "" ] ; then
      dri=""
      dri64=""
   fi

   echo "DEBUG: (hwinfo) - dri: $dri - dri64: $dri64 - driver: $driver" > /var/log/hwinfo-gfx.log

   if  [ "${USENONFREE}" == "yes" ] || [ "${USENONFREE}" == "true" ]; then
      pacman --config "/opt/manjaro/pacman-gfx.conf" -Sy $driver $dri $dri64 xf86-video-vesa --noconfirm &> /dev/null
   else
      pacman --config "/opt/manjaro/pacman-gfx.conf" -Sy $driver $dri $dri64 xf86-video-vesa --noconfirm &> /dev/null
   fi
fi

#do_makeuser
addgroups="video,audio,power,disk,storage,optical,network,lp"
useradd -m -p "" -g users -G $addgroups manjaro
sed -i "s#manjaro.*#manjaro:\$1\$uYIrxnwJ\$a5wTa84YxxYmD.sKX/Lll1:14942:0:99999:7:::#" /etc/shadow

#do_setuplightdm
if [ -e "/usr/sbin/lightdm" ] ; then
   mkdir -p /run/lightdm > /dev/null
   chown -R lightdm:lightdm /run/lightdm > /dev/null
   sed -i -e 's/^.*user-session=.*/user-session=xfce/' /etc/lightdm/lightdm.conf
   sed -i -e 's/^.*autologin-user=.*/autologin-user=manjaro/' /etc/lightdm/lightdm.conf
   sed -i -e 's/^.*autologin-user-timeout=.*/autologin-user-timeout=0/' /etc/lightdm/lightdm.conf
   sed -i -e 's/^.*pam-service=.*/pam-service=lightdm-autologin/' /etc/lightdm/lightdm.conf
   chmod +r /etc/lightdm/lightdm.conf
fi

#do_setupkdm
if [ -e "/usr/share/config/kdm/kdmrc" ] ; then
   sed -i -e 's/^.*AutoLoginUser=.*/AutoLoginUser=manjaro/' /usr/share/config/kdm/kdmrc
   sed -i -e 's/^.*AutoLoginPass=.*/AutoLoginPass=manjaro/' /usr/share/config/kdm/kdmrc
fi

#do_setupgdm
if [ -e "/usr/sbin/gdm" ] ; then
  getent group gdm >/dev/null 2>&1 || groupadd -g 120 gdm
  getent passwd gdm > /dev/null 2>&1 || usr/sbin/useradd -c 'Gnome Display Manager' -u 120 -g gdm -d /var/lib/gdm -s /sbin/nologin gdm
  passwd -l gdm > /dev/null
  chown -R gdm:gdm /var/lib/gdm &> /dev/null
fi

#do_fix_perms
chown root:root /etc/sudoers
chmod 440 /etc/sudoers

#fix_gnome_apps
gconfpkg --install gnome-terminal &> /dev/null
glib-compile-schemas /usr/share/glib-2.0/schemas &> /dev/null
update-desktop-database -q &> /dev/null
gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor &> /dev/null
dconf update &> /dev/null

#do_lang_settings
 	# Determind which language we are using
	if [ "$(echo "${LOCALE}" | grep "de_")" != "" ]; then
		# Setup system for the German language
		
		# Set German Xorg keyboard layout
		sed -i 's#Identifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "de"\n        Option "XkbVariant" "nodeadkeys"#' /etc/X11/xorg.conf.d/10-evdev.conf


	elif [ "$(echo "${LOCALE}" | grep "fr_")" != "" ]; then
		# Setup system for the French language
		
		# Set French Xorg keyboard layout
		sed -i 's#Identifier "evdev keyboard catchall".*#&\n        Option "XkbLayout" "fr"#'       /etc/X11/xorg.conf.d/10-evdev.conf
	fi
