#!/bin/sh

update_pacman_config() {
# configure mirrorlist
wget -O /etc/pacman.d/mirrorlist http://git.manjaro.org/packages-sources/basis/blobs/raw/master/pacman-mirrorlist/mirrorlist &>/dev/null
sed -i 's/# Server/Server/g' -i /etc/pacman.d/mirrorlist
# rankmirrors
cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
rankmirrors -v -n 4 /etc/pacman.d/mirrorlist.backup > /etc/pacman.d/mirrorlist
# update pacman database
pacman -Syy
}

case "$2" in
	up)
		update_pacman_config
	;;
	vpn-up)
		update_pacman_config
	;;
esac
